export const productsData = [
  // 30 data
  // Alat Bantu Pernapasan (idKategori: "1")
  // {
  //   namaProduk: "Nebulizer Portable",
  //   deskripsi: "Alat bantu pernapasan portable untuk terapi inhalasi.",
  //   harga: 650000,
  //   stok: 25,
  //   idKategori: "1",
  //   idToko: "A01",
  //   namaProduk_lowercase: "nebulizer portable",
  // },
  // {
  //   namaProduk: "Oksimeter Pulse",
  //   deskripsi:
  //     "Alat pengukur saturasi oksigen dalam darah dengan akurasi tinggi.",
  //   harga: 350000,
  //   stok: 50,
  //   idKategori: "1",
  //   idToko: "A02",
  //   namaProduk_lowercase: "oksimeter pulse",
  // },
  // {
  //   namaProduk: "Masker Oksigen",
  //   deskripsi: "Masker oksigen untuk pasien yang membutuhkan tambahan oksigen.",
  //   harga: 50000,
  //   stok: 100,
  //   idKategori: "1",
  //   idToko: "A01",
  //   namaProduk_lowercase: "masker oksigen",
  // },
  // {
  //   namaProduk: "Tabung Oksigen 1 Liter",
  //   deskripsi: "Tabung oksigen ukuran 1 liter lengkap dengan regulator.",
  //   harga: 750000,
  //   stok: 10,
  //   idKategori: "1",
  //   idToko: "A03",
  //   namaProduk_lowercase: "tabung oksigen 1 liter",
  // },
  // {
  //   namaProduk: "Ventilator",
  //   deskripsi:
  //     "Alat bantu pernapasan untuk pasien dengan masalah paru-paru berat.",
  //   harga: 15000000,
  //   stok: 3,
  //   idKategori: "1",
  //   idToko: "A02",
  //   namaProduk_lowercase: "ventilator",
  // },
  // {
  //   namaProduk: "BIPAP (Bilevel Positive Airway Pressure)",
  //   deskripsi:
  //     "Alat bantu pernapasan non-invasif untuk terapi pasien dengan masalah pernapasan.",
  //   harga: 12500000,
  //   stok: 7,
  //   idKategori: "1",
  //   idToko: "A01",
  //   namaProduk_lowercase: "bipap",
  // },
  // {
  //   namaProduk: "CPAP (Continuous Positive Airway Pressure)",
  //   deskripsi: "Mesin CPAP untuk terapi gangguan tidur apnea.",
  //   harga: 8500000,
  //   stok: 8,
  //   idKategori: "1",
  //   idToko: "A03",
  //   namaProduk_lowercase: "cpap",
  // },
  // {
  //   namaProduk: "Konsentrator Oksigen 5 Liter",
  //   deskripsi:
  //     "Alat untuk menghasilkan oksigen secara terus-menerus bagi pasien.",
  //   harga: 4500000,
  //   stok: 6,
  //   idKategori: "1",
  //   idToko: "A02",
  //   namaProduk_lowercase: "konsentrator oksigen 5 liter",
  // },
  // {
  //   namaProduk: "Kanula Nasal",
  //   deskripsi:
  //     "Selang oksigen yang digunakan untuk membantu suplai oksigen melalui hidung.",
  //   harga: 25000,
  //   stok: 150,
  //   idKategori: "1",
  //   idToko: "A01",
  //   namaProduk_lowercase: "kanula nasal",
  // },
  // {
  //   namaProduk: "Pipet Aspirasi Oksigen",
  //   deskripsi:
  //     "Alat untuk membantu proses aspirasi pada pasien yang membutuhkan oksigen tambahan.",
  //   harga: 75000,
  //   stok: 100,
  //   idKategori: "1",
  //   idToko: "A03",
  //   namaProduk_lowercase: "pipet aspirasi oksigen",
  // },

  // // Alat Pengukur Kesehatan (idKategori: "2")
  // {
  //   namaProduk: "Termometer Digital",
  //   deskripsi: "Termometer digital dengan hasil akurat dan cepat.",
  //   harga: 120000,
  //   stok: 80,
  //   idKategori: "2",
  //   idToko: "A01",
  //   namaProduk_lowercase: "termometer digital",
  // },
  // {
  //   namaProduk: "Tensimeter Manual",
  //   deskripsi: "Tensimeter untuk mengukur tekanan darah dengan metode manual.",
  //   harga: 250000,
  //   stok: 50,
  //   idKategori: "2",
  //   idToko: "A02",
  //   namaProduk_lowercase: "tensimeter manual",
  // },
  // {
  //   namaProduk: "Glucometer",
  //   deskripsi: "Alat pengukur kadar gula darah dengan strip tes.",
  //   harga: 350000,
  //   stok: 40,
  //   idKategori: "2",
  //   idToko: "A03",
  //   namaProduk_lowercase: "glucometer",
  // },
  // {
  //   namaProduk: "Timbangan Badan Digital",
  //   deskripsi: "Timbangan badan digital dengan sensor akurasi tinggi.",
  //   harga: 200000,
  //   stok: 75,
  //   idKategori: "2",
  //   idToko: "A01",
  //   namaProduk_lowercase: "timbangan badan digital",
  // },
  // {
  //   namaProduk: "Pengukur Tinggi Badan",
  //   deskripsi: "Alat untuk mengukur tinggi badan dengan akurat.",
  //   harga: 150000,
  //   stok: 60,
  //   idKategori: "2",
  //   idToko: "A02",
  //   namaProduk_lowercase: "pengukur tinggi badan",
  // },
  // {
  //   namaProduk: "Monitor Tekanan Darah Digital",
  //   deskripsi: "Alat pengukur tekanan darah otomatis dengan layar digital.",
  //   harga: 600000,
  //   stok: 25,
  //   idKategori: "2",
  //   idToko: "A03",
  //   namaProduk_lowercase: "monitor tekanan darah digital",
  // },
  // {
  //   namaProduk: "Stetoskop",
  //   deskripsi:
  //     "Stetoskop berkualitas untuk mendengar suara jantung dan paru-paru.",
  //   harga: 175000,
  //   stok: 100,
  //   idKategori: "2",
  //   idToko: "A01",
  //   namaProduk_lowercase: "stetoskop",
  // },
  // {
  //   namaProduk: "Termometer Inframerah",
  //   deskripsi:
  //     "Termometer inframerah tanpa kontak, ideal untuk mengukur suhu tubuh.",
  //   harga: 400000,
  //   stok: 50,
  //   idKategori: "2",
  //   idToko: "A02",
  //   namaProduk_lowercase: "termometer inframerah",
  // },
  // {
  //   namaProduk: "Tensimeter Digital",
  //   deskripsi: "Tensimeter digital otomatis dengan tampilan layar besar.",
  //   harga: 750000,
  //   stok: 30,
  //   idKategori: "2",
  //   idToko: "A03",
  //   namaProduk_lowercase: "tensimeter digital",
  // },
  // {
  //   namaProduk: "Oxymeter",
  //   deskripsi: "Alat untuk mengukur kadar oksigen dalam darah (SpO2).",
  //   harga: 300000,
  //   stok: 60,
  //   idKategori: "2",
  //   idToko: "A01",
  //   namaProduk_lowercase: "oxymeter",
  // },

  // // Alat Sterilisasi (idKategori: "3")
  // {
  //   namaProduk: "Sterilisator UV Portable",
  //   deskripsi: "Sterilisator dengan sinar UV untuk membunuh bakteri dan virus.",
  //   harga: 500000,
  //   stok: 45,
  //   idKategori: "3",
  //   idToko: "A02",
  //   namaProduk_lowercase: "sterilisator uv portable",
  // },
  // {
  //   namaProduk: "Autoclave Mini",
  //   deskripsi: "Autoclave mini untuk sterilisasi peralatan medis.",
  //   harga: 3000000,
  //   stok: 12,
  //   idKategori: "3",
  //   idToko: "A03",
  //   namaProduk_lowercase: "autoclave mini",
  // },
  // {
  //   namaProduk: "Disinfektan Spray",
  //   deskripsi: "Spray disinfektan untuk membunuh kuman pada permukaan benda.",
  //   harga: 50000,
  //   stok: 200,
  //   idKategori: "3",
  //   idToko: "A01",
  //   namaProduk_lowercase: "disinfektan spray",
  // },
  // {
  //   namaProduk: "Hand Sanitizer 500ml",
  //   deskripsi: "Hand sanitizer 500ml dengan kandungan alkohol 70%.",
  //   harga: 75000,
  //   stok: 150,
  //   idKategori: "3",
  //   idToko: "A02",
  //   namaProduk_lowercase: "hand sanitizer 500ml",
  // },
  // {
  //   namaProduk: "Sterilisator Uap",
  //   deskripsi:
  //     "Sterilisator uap untuk sterilisasi peralatan medis dengan uap panas.",
  //   harga: 1200000,
  //   stok: 8,
  //   idKategori: "3",
  //   idToko: "A03",
  //   namaProduk_lowercase: "sterilisator uap",
  // },
  // {
  //   namaProduk: "Lampu UV Sterilisasi",
  //   deskripsi:
  //     "Lampu UV yang digunakan untuk mensterilkan ruangan dari bakteri dan virus.",
  //   harga: 850000,
  //   stok: 10,
  //   idKategori: "3",
  //   idToko: "A01",
  //   namaProduk_lowercase: "lampu uv sterilisasi",
  // },
  // {
  //   namaProduk: "Mesin Sterilisasi Air",
  //   deskripsi:
  //     "Mesin untuk mensterilkan air yang digunakan dalam proses medis.",
  //   harga: 4500000,
  //   stok: 4,
  //   idKategori: "3",
  //   idToko: "A02",
  //   namaProduk_lowercase: "mesin sterilisasi air",
  // },
  // {
  //   namaProduk: "Sterilisator Uap Bertekanan",
  //   deskripsi:
  //     "Sterilisator dengan uap bertekanan tinggi untuk peralatan medis.",
  //   harga: 7000000,
  //   stok: 5,
  //   idKategori: "3",
  //   idToko: "A03",
  //   namaProduk_lowercase: "sterilisator uap bertekanan",
  // },
  // {
  //   namaProduk: "Disinfektan Cair 1 Liter",
  //   deskripsi: "Cairan disinfektan untuk sterilisasi ruangan dan peralatan.",
  //   harga: 100000,
  //   stok: 100,
  //   idKategori: "3",
  //   idToko: "A01",
  //   namaProduk_lowercase: "disinfektan cair 1 liter",
  // },
  // {
  //   namaProduk: "Mesin Fogging Sterilisasi",
  //   deskripsi: "Mesin fogging untuk menyemprotkan disinfektan ke area luas.",
  //   harga: 3500000,
  //   stok: 6,
  //   idKategori: "3",
  //   idToko: "A02",
  //   namaProduk_lowercase: "mesin fogging sterilisasi",
  // },
  {
    namaProduk: "Termometer Digital Anak",
    deskripsi:
      "Termometer digital untuk mengukur suhu anak-anak secara akurat.",
    harga: 150000,
    stok: 50,
    idKategori: "2", // Alat Pengukur Kesehatan
    idToko: "A01",
    namaProduk_lowercase: "termometer digital anak",
  },
  {
    namaProduk: "Termometer Inframerah Non-Kontak",
    deskripsi: "Termometer inframerah non-kontak untuk pengukuran cepat.",
    harga: 350000,
    stok: 30,
    idKategori: "2",
    idToko: "A02",
    namaProduk_lowercase: "termometer inframerah non-kontak",
  },
  {
    namaProduk: "Termometer Medis Klinik",
    deskripsi: "Termometer klinik untuk pengukuran suhu tubuh di rumah sakit.",
    harga: 500000,
    stok: 20,
    idKategori: "2",
    idToko: "A03",
    namaProduk_lowercase: "termometer medis klinik",
  },
  {
    namaProduk: "Termometer Telinga Digital",
    deskripsi: "Termometer digital untuk mengukur suhu melalui telinga.",
    harga: 200000,
    stok: 60,
    idKategori: "2",
    idToko: "A01",
    namaProduk_lowercase: "termometer telinga digital",
  },
  {
    namaProduk: "Termometer Kulit Elektronik",
    deskripsi:
      "Termometer elektronik untuk mengukur suhu kulit secara presisi.",
    harga: 175000,
    stok: 40,
    idKategori: "2",
    idToko: "A02",
    namaProduk_lowercase: "termometer kulit elektronik",
  },
  {
    namaProduk: "Termometer Otomatis Ruangan",
    deskripsi:
      "Termometer otomatis untuk memantau suhu ruangan secara real-time.",
    harga: 250000,
    stok: 25,
    idKategori: "2",
    idToko: "A03",
    namaProduk_lowercase: "termometer otomatis ruangan",
  },
  {
    namaProduk: "Termometer Air Digital",
    deskripsi: "Termometer digital untuk mengukur suhu air dengan akurat.",
    harga: 100000,
    stok: 35,
    idKategori: "2",
    idToko: "A01",
    namaProduk_lowercase: "termometer air digital",
  },
  {
    namaProduk: "Termometer Multifungsi",
    deskripsi:
      "Termometer multifungsi yang dapat digunakan di berbagai kondisi.",
    harga: 300000,
    stok: 15,
    idKategori: "2",
    idToko: "A02",
    namaProduk_lowercase: "termometer multifungsi",
  },
  {
    namaProduk: "Termometer Dahi Non-Kontak",
    deskripsi:
      "Termometer non-kontak yang praktis digunakan untuk mengukur suhu dahi.",
    harga: 275000,
    stok: 50,
    idKategori: "2",
    idToko: "A03",
    namaProduk_lowercase: "termometer dahi non-kontak",
  },
  {
    namaProduk: "Termometer Ketiak Elektronik",
    deskripsi: "Termometer elektronik yang nyaman digunakan di area ketiak.",
    harga: 120000,
    stok: 70,
    idKategori: "2",
    idToko: "A01",
    namaProduk_lowercase: "termometer ketiak elektronik",
  },
  {
    namaProduk: "Termometer Ruangan Digital",
    deskripsi: "Termometer digital yang ideal untuk memantau suhu ruangan.",
    harga: 200000,
    stok: 80,
    idKategori: "2",
    idToko: "A02",
    namaProduk_lowercase: "termometer ruangan digital",
  },
  {
    namaProduk: "Termometer Air Raksa",
    deskripsi:
      "Termometer tradisional berbasis air raksa untuk penggunaan klinik.",
    harga: 80000,
    stok: 100,
    idKategori: "2",
    idToko: "A03",
    namaProduk_lowercase: "termometer air raksa",
  },
];
